export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOG_OUT = 'LOG_OUT';
export const AUTO_SIGNUP_ON_REFRESH = 'AUTO_SIGNUP_ON_REFRESH';

export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';
export const FETCH_ALL_LICENSES = 'FETCH_ALL_LICENSES';

export const FETCH_ONE_LICENSE = 'FETCH_ONE_LICENSE';

export const UPDATE_LICENSE = 'UPDATE_LICENSE';
export const UPDATE_LICENSE_START = 'UPDATE_LICENSE_START';
export const UPDATE_LICENSE_SUCCESS = 'UPDATE_LICENSE_SUCCESS';
export const UPDATE_LICENSE_FAIL = 'UPDATE_LICENSE_FAIL';

export const DELETE_LICENSE = 'DELETE_LICENSE';
export const DELETE_LICENSE_START = 'DELETE_LICENSE_START';
export const DELETE_LICENSE_SUCCESS = 'DELETE_LICENSE_SUCCESS';
export const DELETE_LICENSE_FAIL = 'DELETE_LICENSE_FAIL';

export const SHOW_MODAL = 'SHOW_MODAL';
export const CANCEL_MODAL ='CANCEL_MODAL';

export const ADD_LICENSE = 'ADD_LICENSE';
export const ADD_LICENSE_START = 'ADD_LICENSE_START';
export const ADD_LICENSE_SUCCESS = 'ADD_LICENSE_SUCCESS';
export const ADD_LICENSE_FAIL = 'ADD_LICENSE_FAIL';

